import {
	Menu,
	LayoutDashboard,
	User,
	Users,
	MessageSquare,
	Home,
	Image,
	Pin,
	Smile,
	Heart,
	Trash2,
	SendHorizonal,
	Search,
	LogOut,
	ArrowLeft,
	SquarePen,
	Pencil,
	Bell,
	Settings,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	X,
	Calendar,
	Newspaper,
	Plus,
	MoreHorizontal,
	Bookmark,
	MessageCircle,
	Share2,
	Clock,
	Sun,
	Moon,
	Monitor,
	Lock,
	Eye,
	EyeOff,
	Shield,
	UserX,
} from 'lucide-react';

// If you update an alias, you must also update it in each component that uses the icon!
export const Icons = {
	home: Home,
	dashboard: LayoutDashboard,
	user: User,
	members: Users,
	groupChats: MessageCircle,
	message: MessageSquare,
	menu: Menu,
	image: Image,
	pin: Pin,
	smile: Smile,
	heart: Heart,
	trash: Trash2,
	send: SendHorizonal,
	search: Search,
	leave: LogOut,
	arrowleft: ArrowLeft,
	edit: SquarePen,
	pencil: Pencil,
	bell: Bell,
	settings: Settings,
	chevronDown: ChevronDown,
	chevronLeft: ChevronLeft,
	chevronRight: ChevronRight,
	close: X,
	calendar: Calendar,
	newsFeed: Newspaper,
	plus: Plus,
	more: MoreHorizontal,
	bookmark: Bookmark,
	comment: MessageCircle,
	share: Share2,
	clock: Clock,
	sun: Sun,
	moon: Moon,
	monitor: Monitor,
	lock: Lock,
	eye: Eye,
	eyeOff: EyeOff,
	shield: Shield,
	userX: UserX,
}